name: Deploy to Hostinger

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Hostinger via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 217.196.54.226
          port: 65002
          username: u304643867
          password: ${{ secrets.HOSTINGER_PASS }}
          script: |
            cd ~/domains/deoia.com/public_html/anahitemoltzinbnb/wp-content/plugins/wp-agenda-automatizada
            rm -rf *
            git clone https://github.com/RobertoTD/wp-agenda-automatizada.git .